### PR TITLE
skin.estuary: Improved the player process info

### PR DESCRIPTION
**Pull request by frodo19**
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Portisch** [comment]
So this is how it looks now?
screenshot00005

In my opinion `Video codec` and `Video resolution` can be dropped as it's already be covered by `Video stream` and `Video decoder`.  `Video stream` is the input, `Display mode` the output format.

**Comment by frodo19** [comment]
Do you should like someting this? 
gh

**Comment by frodo19** [comment]
Hmm.. the pr gone again... its synced then automatically closed..

**Comment by Portisch** [comment]
I did rebase xbmc, maybe this caused the close.
I am not sure about this `System FPS`. It might confuse people because its different to media FPS. Maybe rename it or drop it as it's not very useful anyway? Why should anybody care about the UI FPS during video playback?

**Comment by frodo19** [comment]
> I did rebase xbmc, maybe this caused the close. I am not sure about this `System FPS`. It might confuse people because its different to media FPS. Maybe rename it or drop it as it's not very useful anyway? Why should anybody care about the UI FPS during video playback?

System fps is the current video output fps. That can be different to the source video fps. People like to see if that synced or not. 
But when you will , I can drop that too..

**Comment by Portisch** [comment]
We think it's the UI fps and not related to video fps. It does also not match any time. So please drop it, yes.

**Comment by Portisch** [comment]
We think it's the UI fps and not related to video fps. It does also not match any time. So please drop it, yes.

**Pull request closed without merging**
